export enum TypeEvent {
  CONCERT = "CONCERT",
  SPORT = "SPORT",
  CONFERENCE = "CONFERENCE"
}

export enum TypeTheme {
  PROGRAMMING = "PROGRAMMING",  
  WEB_DEVELOPMENT = "WEB_DEVELOPMENT",  
  MOBILE_DEVELOPMENT = "MOBILE_DEVELOPMENT",  
  CLOUD_COMPUTING = "CLOUD_COMPUTING",  
  CYBERSECURITY = "CYBERSECURITY",  
  DEVOPS = "DEVOPS",  
  BLOCKCHAIN = "BLOCKCHAIN",  
  IOT = "IOT",  
  BIG_DATA = "BIG_DATA",  
  MACHINE_LEARNING = "MACHINE_LEARNING",  
  COMPUTER_VISION = "COMPUTER_VISION",  
  NETWORKING = "NETWORKING",  
  DATABASE = "DATABASE",  
  SOFTWARE_ENGINEERING = "SOFTWARE_ENGINEERING",  
  UI_UX = "UI_UX",  
  EMBEDDED_SYSTEMS = "EMBEDDED_SYSTEMS",  
  QUANTUM_COMPUTING = "QUANTUM_COMPUTING",  
  GAME_DEVELOPMENT = "GAME_DEVELOPMENT"
}

export enum TypeWeather {
  SUNNY = "SUNNY",
  RAINY = "RAINY",
  CLOUDY = "CLOUDY"
}
